{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"M_ComplianceReport_ActualsExpected\",\"M_ComplianceReport_WetForecasts\",\"dimRegulatoryInstrument\",\"dimForecastVintage\",\"fctTonnage\",\"fctWetCYForecasts\",\"fxDateTable\",\"fxStartDate\",\"fxEndDate\",\"dimDate\",\"_Measures\",\"_Period\",\"fctWetCYActuals\",\"M_ComplianceReport_MetroWetActuals\",\"_DataRefresh\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "M_ComplianceReport_ActualsExpected",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Data Source",
          "    Source = Csv.Document(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Untitled - Compliance\\Other Files\\ActualsExpected_Fake.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    ",
          "    // Promote first row of csv file as headers",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    ",
          "    // Set column data types",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"RegulatoryInstrumentLimitId\", Int64.Type}, {\"InstrumentLabel\", type text}, {\"ReferenceNumber\", type text}, {\"ReportingEntity\", type text}, {\"Direction\", type text}, {\"Material\", type text}, {\"Destination\", type text}, {\"TonnageLimit\", Int64.Type}, {\"Inactive\", Int64.Type}, {\"AllocRelated\", Int64.Type}, {\"RepPeriod\", type date}, {\"ActualTons\", type number}, {\"ExpectedTons\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "9829a8c3-1ac3-47f1-9200-62613f7a5c1e",
        "queryGroup": "Source"
      },
      {
        "name": "M_ComplianceReport_WetForecasts",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Data Source",
          "    Source = Csv.Document(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Untitled - Compliance\\Other Files\\M_ComplianceReport_WetForecasts_v2.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    ",
          "    // Promote first row of csv file as headers",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    ",
          "    // Set column data types",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"VintageName\", type text}, {\"RepPeriod\", type date}, {\"Tons\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "d4a7bbf9-8999-4356-828d-6d8f0b10c57e",
        "queryGroup": "Source"
      },
      {
        "name": "fxDateTable",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = let fnDateTable = ( StartDate as date, EndDate as date, optional FYStartMonthNum as number, optional Holidays as list, optional WDStartNum as number, optional AddRelativeNetWorkdays as logical ) as table =>",
          "  let",
          "      FYStartMonth = List.Select( {1..12}, each _ = FYStartMonthNum ){0}? ?? 1,",
          "      WDStart = List.Select( {0..1}, each _ = WDStartNum ){0}? ?? 0,",
          "      CurrentDate = Date.From( DateTime.FixedLocalNow()),",
          "      DayCount = Duration.Days( Duration.From( EndDate - StartDate)) +1,",
          "      Source = List.Dates( StartDate, DayCount, #duration(1,0,0,0)),",
          "      AddToday = if EndDate < CurrentDate then List.Combine( {Source, {CurrentDate}}) else Source,",
          "      ToTable = Table.FromList(AddToday, Splitter.SplitByNothing(), type table [Date = Date.Type] ),",
          "      InsertYear = Table.AddColumn(ToTable, \"Year\", each Date.Year([Date]), type number),",
          "      InsertYearOffset = Table.AddColumn(InsertYear, \"CurrYearOffset\", each Date.Year([Date]) - Date.Year( Date.From(CurrentDate)), type number),",
          "      InsertCompletedYear = Table.AddColumn(InsertYearOffset, \"YearCompleted\", each Date.EndOfYear([Date]) < Date.From( Date.EndOfYear(CurrentDate)), type logical),",
          "",
          "      InsertQuarterNum = Table.AddColumn(InsertCompletedYear, \"Quarter Number\", each Date.QuarterOfYear([Date]), type number),",
          "      InsertQuarter = Table.AddColumn(InsertQuarterNum, \"Quarter\", each \"Q\" & Number.ToText([Quarter Number]), type text),",
          "      InsertStartOfQuarter = Table.AddColumn(InsertQuarter, \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
          "      InsertEndOfQuarter = Table.AddColumn(InsertStartOfQuarter, \"End of Quarter\", each Date.EndOfQuarter([Date]), type date),",
          "      InsertCalendarQtr = Table.AddColumn(InsertEndOfQuarter, \"Quarter & Year\", each \"Q\" & Number.ToText( Date.QuarterOfYear([Date])) & Date.ToText([Date], [Format = \" yyyy\"]), type text),",
          "      InsertQuarternYear = Table.AddColumn(InsertCalendarQtr, \"QuarternYear\", each [Year] * 10 + [Quarter Number], type number),",
          "      InsertQuarterOffset = Table.AddColumn(InsertQuarternYear, \"CurrQuarterOffset\", each ((4 * Date.Year([Date])) +  Date.QuarterOfYear([Date])) - ((4 * Date.Year(Date.From(CurrentDate))) +  Date.QuarterOfYear(Date.From(CurrentDate))), type number),",
          "      InsertCompletedQuarter = Table.AddColumn(InsertQuarterOffset, \"QuarterCompleted\", each Date.EndOfQuarter([Date]) < Date.From(Date.EndOfQuarter(CurrentDate)), type logical),",
          "",
          "      InsertMonth = Table.AddColumn(InsertCompletedQuarter, \"Month\", each Date.Month([Date]), type number),",
          "      InsertStartOfMonth = Table.AddColumn(InsertMonth, \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
          "      InsertEndOfMonth = Table.AddColumn(InsertStartOfMonth, \"End of Month\", each Date.EndOfMonth([Date]), type date),",
          "      InsertCalendarMonth = Table.AddColumn(InsertEndOfMonth, \"Month & Year\", each Text.Proper( Date.ToText([Date], [Format = \"MMM yyyy\"])), type text),",
          "      InsertMonthnYear = Table.AddColumn(InsertCalendarMonth , \"MonthnYear\", each [Year] * 100 + [Month], type number),",
          "      InsertMonthOffset = Table.AddColumn(InsertMonthnYear, \"CurrMonthOffset\", each ((12 * Date.Year([Date])) +  Date.Month([Date])) - ((12 * Date.Year(Date.From(CurrentDate))) +  Date.Month(Date.From(CurrentDate))), type number),",
          "      InsertCompletedMonth = Table.AddColumn(InsertMonthOffset, \"MonthCompleted\", each Date.EndOfMonth([Date]) < Date.From(Date.EndOfMonth(CurrentDate)), type logical),",
          "      InsertMonthName = Table.AddColumn(InsertCompletedMonth, \"Month Name\", each Text.Proper( Date.ToText([Date], \"MMMM\")), type text),",
          "      InsertMonthShort = Table.AddColumn( InsertMonthName, \"Month Short\", each Text.Proper( Date.ToText([Date], \"MMM\")), type text),",
          "      InsertMonthInitial = Table.AddColumn(InsertMonthShort, \"Month Initial\", each Text.Start([Month Name], 1) & Text.Repeat( Character.FromNumber(8203), Date.Month([Date]) ), type text),",
          "      InsertDayOfMonth = Table.AddColumn(InsertMonthInitial, \"Day of Month\", each Date.Day([Date]), type number),",
          "  ",
          "      InsertWeekNumber = Table.AddColumn(InsertDayOfMonth, \"Week Number\", each",
          "        if Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0",
          "        then Number.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)",
          "        else if (Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53 and (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))",
          "        then 1 else Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7), type number),",
          "      InsertStartOfWeek = Table.AddColumn(InsertWeekNumber, \"Start of Week\", each Date.StartOfWeek([Date], Day.Monday), type date),",
          "      InsertWeekEnding = Table.AddColumn(InsertStartOfWeek, \"End of Week\", each Date.EndOfWeek( [Date], Day.Monday), type date),",
          "      InsertCalendarWk = Table.AddColumn(InsertWeekEnding, \"Week & Year\", each \"W\" & Text.PadStart( Text.From( [Week Number] ), 2, \"0\") & \" \" & Text.From(Date.Year( Date.AddDays( Date.StartOfWeek([Date], Day.Monday), 3 ))), type text ),",
          "      InsertWeeknYear = Table.AddColumn(InsertCalendarWk, \"WeeknYear\", each Date.Year( Date.AddDays( Date.StartOfWeek([Date], Day.Monday), 3 )) * 100 + [Week Number],  Int64.Type),",
          "      InsertWeekOffset = Table.AddColumn(InsertWeeknYear, \"CurrWeekOffset\", each (Number.From(Date.StartOfWeek([Date], Day.Monday))-Number.From(Date.StartOfWeek(CurrentDate, Day.Monday)))/7, type number),",
          "      InsertCompletedWeek = Table.AddColumn(InsertWeekOffset, \"WeekCompleted\", each Date.EndOfWeek( [Date], Day.Monday) < Date.From(Date.EndOfWeek(CurrentDate, Day.Monday)), type logical),",
          "  ",
          "      InsertDayWeek = Table.AddColumn(InsertCompletedWeek, \"Day of Week Number\", each Date.DayOfWeek([Date], Day.Monday) + WDStart, Int64.Type),",
          "      InsertDayName = Table.AddColumn(InsertDayWeek, \"Day of Week Name\", each Text.Proper( Date.ToText([Date], \"dddd\" )), type text),",
          "      InsertDayInitial = Table.AddColumn(InsertDayName, \"Day of Week Initial\", each Text.Proper(Text.Start([Day of Week Name], 1)) & Text.Repeat( Character.FromNumber(8203), Date.DayOfWeek([Date], Day.Monday) + WDStart ), type text),",
          "      InsertDayOfYear = Table.AddColumn(InsertDayInitial, \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),",
          "      InsertDayInt = Table.AddColumn(InsertDayOfYear, \"DateInt\", each [Year] * 10000 + [Month] * 100 + [Day of Month], type number),",
          "      InsertDayOffset = Table.AddColumn(InsertDayInt, \"CurrDayOffset\", each Number.From([Date]) - Number.From(CurrentDate), type number),",
          "      InsertIsAfterToday = Table.AddColumn(InsertDayOffset, \"IsAfterToday\", each not ([Date] <= Date.From(CurrentDate)), type logical),",
          "      InsertIsWorkingDay = Table.AddColumn(InsertIsAfterToday, \"IsWeekDay\", each if Date.DayOfWeek([Date], Day.Monday) > 4 then false else true, type logical),",
          "      InsertIsHoliday = Table.AddColumn(InsertIsWorkingDay, \"IsHoliday\", each if Holidays = null then \"Unknown\" else List.Contains( Holidays, [Date] ), if Holidays = null then type text else type logical),",
          "      InsertIsBusinessDay = Table.AddColumn(InsertIsHoliday, \"IsBusinessDay\", each if [IsWeekDay] = true and [IsHoliday] <> true then true else false, type logical),",
          "      InsertDayType = Table.AddColumn(InsertIsBusinessDay, \"Day Type\", each if [IsHoliday] = true then \"Holiday\" else if [IsWeekDay] = false then \"Weekend\" else if [IsWeekDay] = true then \"Weekday\" else null, type text),",
          "",
          "      InsertISOYear = Table.AddColumn( InsertDayType, \"ISO Year\", each Date.Year( Date.AddDays( Date.StartOfWeek([Date], Day.Monday), 3 )), type number),",
          "      InsertISOqNum = Table.AddColumn(InsertISOYear, \"ISO Quarter Number\", each if [Week Number] >39 then 4 else if [Week Number] >26 then 3 else if [Week Number] >13 then 2 else 1, Int64.Type),",
          "      InsertISOqtr = Table.AddColumn(InsertISOqNum, \"ISO Quarter\", each \"Q\" & Number.ToText([ISO Quarter Number]), type text),",
          "      InsertISOQuarter = Table.AddColumn(InsertISOqtr, \"ISO Quarter & Year\", each \"Q\" & Number.ToText([ISO Quarter Number]) & \" \" & Number.ToText([ISO Year]), type text),",
          "      InsertISOqNy = Table.AddColumn(InsertISOQuarter, \"ISO QuarternYear\", each [ISO Year] * 10 + [ISO Quarter Number], type number),",
          "",
          "      // BufferTable = Table.Buffer(Table.Distinct( InsertISOqNy[[ISO Year], [DateInt]])),",
          "      // InsertISOday = Table.AddColumn(InsertISOqNy, \"ISO Day of Year\", (OT) => Table.RowCount( Table.SelectRows( BufferTable, (IT) => IT[DateInt] <= OT[DateInt] and IT[ISO Year] = OT[ISO Year])),  Int64.Type),",
          "      AddFY = Table.AddColumn(InsertISOqNy, \"Fiscal Year\", each \"FY\" & (if [Month] >= FYStartMonth and FYStartMonth >1 then Text.From([Year] +1) else Text.From([Year])), type text),",
          "      //AddFYs = Table.AddColumn(AddFY, \"Fiscal Year short\", each \"FY\" & (if [Month] >= FYStartMonth and FYStartMonth >1 then Text.PadEnd( Text.End( Text.From([Year] +1), 2), 2, \"0\") else Text.End( Text.From([Year]), 2)), type text),",
          "      AddFQ = Table.AddColumn(AddFY, \"Fiscal Quarter\", each \"FQ\" & Text.From( Number.RoundUp( Date.Month( Date.AddMonths( [Date], - (FYStartMonth -1) )) / 3 )) & \" \" & (if [Month] >= FYStartMonth and FYStartMonth >1 then Text.From([Year] +1) else Text.From([Year])), type text),",
          "      AddFQnYr = Table.AddColumn(AddFQ, \"FQuarternYear\", each (if [Month] >= FYStartMonth and FYStartMonth >1 then [Year] +1 else [Year]) * 10 + Number.RoundUp( Date.Month( Date.AddMonths( [Date], - (FYStartMonth -1) )) / 3 ), type number),",
          "      AddFM = Table.AddColumn(AddFQnYr, \"Fiscal Period Number\", each if [Month] >= FYStartMonth and FYStartMonth >1 then [Month] - (FYStartMonth-1) else if [Month] >= FYStartMonth and FYStartMonth =1 then [Month] else [Month] + (12-FYStartMonth+1), type number),",
          "      AddFP = Table.AddColumn(AddFM, \"Fiscal Period\", each \"FP\" & Text.PadStart( Text.From([Fiscal Period Number]), 2, \"0\") & \" \" & (if [Month] >= FYStartMonth and FYStartMonth >1 then Text.From([Year] +1) else Text.From([Year])), type text),",
          "      AddFMnYr = Table.AddColumn(AddFP , \"FPeriodnYear\", each (if [Month] >= FYStartMonth and FYStartMonth >1 then [Year] +1 else [Year]) * 100 + [Fiscal Period Number], type number),",
          "      FYCalendarStart = #date( Date.Year(StartDate)-1, FYStartMonth, 1 ),",
          "      InsertFFD = Table.AddColumn( AddFMnYr, \"FiscalFirstDay\", each if [Month] >= FYStartMonth and FYStartMonth >1 then #date( Date.Year([Date])+1, FYStartMonth, 1) else #date( Date.Year([Date]), FYStartMonth, 1), type date ),",
          "",
          "      InitTable = Table.FromList( List.Transform( {Number.From(FYCalendarStart) .. Number.From(EndDate)}, Date.From), Splitter.SplitByNothing(), type table [DateFW = Date.Type]),",
          "      AddFFD = Table.AddColumn( InitTable, \"FiscalFirstDay\", each if Date.Month([DateFW]) < FYStartMonth then #date(Date.Year([DateFW]), FYStartMonth, 1) else #date(Date.Year([DateFW]) + 1, FYStartMonth, 1)),",
          "      AddFWSD = Table.AddColumn( AddFFD, \"FWStartDate\", each Date.AddYears(Date.StartOfWeek([DateFW], Day.Monday), 1)),",
          "      Group1 = Table.Group( AddFWSD, {\"FiscalFirstDay\", \"FWStartDate\"}, {{\"AllRows\", each _, type table [DateFW = nullable date, FiscalFirstDay = date, FWStartDate = date]}}),",
          "      Group2 = Table.Group( Group1, {\"FiscalFirstDay\"}, {{\"AllRows2\", each _, type table [FiscalFirstDay = date, FWStartDate = date, AllRows = table]}}),",
          "      AddIndex = Table.AddColumn( Group2, \"Custom\", each Table.AddIndexColumn([AllRows2], \"Fiscal Week Number\", 1, 1) )[[Custom]],",
          "      ExpandG2 = Table.ExpandTableColumn( AddIndex, \"Custom\", {\"FiscalFirstDay\", \"FWStartDate\", \"AllRows\", \"Fiscal Week Number\"}, {\"FiscalFirstDay\", \"FWStartDate\", \"AllRows\", \"Fiscal Week Number\"}), ",
          "      ExpandG1 = Table.ExpandTableColumn( ExpandG2, \"AllRows\", {\"DateFW\"}, {\"DateFW\"} )[[DateFW], [Fiscal Week Number]],",
          "      MergeFYW = Table.Join( InsertFFD, {\"Date\"}, ExpandG1, {\"DateFW\"}, JoinKind.LeftOuter, JoinAlgorithm.SortMerge ),",
          "      FWlogic = List.Contains( {null}, FYStartMonthNum),",
          "      UpdateFYWeek = if FWlogic then Table.ReplaceValue(MergeFYW, each [Fiscal Week Number], each if FYStartMonth =1 then [Week Number] else [Fiscal Week Number], Replacer.ReplaceValue, {\"Fiscal Week Number\"}) else MergeFYW,",
          "      AddFYW = Table.AddColumn( UpdateFYWeek, \"Fiscal Week\", each if FWlogic then \"F\" & [#\"Week & Year\"] else if FYStartMonth =1 then \"FW\" & Text.PadStart( Text.From([Fiscal Week Number]), 2, \"0\") & Date.ToText([Date], \" yyyy\") else if Date.Month([Date]) < FYStartMonth then \"FW\" & Text.PadStart( Text.From([Fiscal Week Number]), 2, \"0\") & Date.ToText([Date], \" yyyy\") else \"FW\" & Text.PadStart(Text.From([Fiscal Week Number]), 2, \"0\") & \" \" & Text.From( Date.Year([Date])+1), type text),",
          "      InsertFWeeknYear = Table.AddColumn(AddFYW, \"FWeeknYear\", each if FWlogic then [WeeknYear] else (if FYStartMonth =1 then Date.Year([Date]) else if Date.Month([Date]) < FYStartMonth then Date.Year([Date]) else Date.Year([Date])+1) * 100 + [Fiscal Week Number],  Int64.Type),",
          "      ",
          "      CurrentDateRecord = Table.SelectRows(InsertFWeeknYear, each ([Date] = CurrentDate)),",
          "      CurrentISOyear = CurrentDateRecord{0}[ISO Year],",
          "      CurrentISOqtr = CurrentDateRecord{0}[ISO Quarter Number],",
          "      CurrentYear = CurrentDateRecord{0}[Year],",
          "      CurrentMonth = CurrentDateRecord{0}[Month],",
          "      CurrentFiscalFirstDay = CurrentDateRecord{0}[FiscalFirstDay],",
          "      PrevFiscalFirstDay = Date.AddYears(CurrentFiscalFirstDay, -1),",
          "      CurrentFY = CurrentDateRecord{0}[Fiscal Year],",
          "      CurrentFQ = CurrentDateRecord{0}[FQuarternYear],",
          "      CurrentFP = CurrentDateRecord{0}[FPeriodnYear],",
          "      CurrentFW = CurrentDateRecord{0}[FWeeknYear],",
          "",
          "      InsertISOYrOffset = Table.AddColumn(InsertFWeeknYear, \"ISO CurrYearOffset\", each [ISO Year] - CurrentISOyear, type number),",
          "      InsertISOQtrOffset = Table.AddColumn(InsertISOYrOffset, \"ISO CurrQuarterOffset\", each ((4 * [ISO Year]) +  [ISO Quarter Number]) - ((4 * CurrentISOyear) + CurrentISOqtr), type number),",
          "      InsertFYoffset = Table.AddColumn(InsertISOQtrOffset, \"Fiscal CurrYearOffset\", each try (if [Month] >= FYStartMonth then [Year]+1 else [Year]) - (if CurrentMonth >= FYStartMonth then CurrentYear+1 else CurrentYear) otherwise null, type number),",
          "      InsertCurrentFY = Table.AddColumn(InsertFYoffset, \"IsCurrentFY\", each if [Fiscal Year] = CurrentFY then true else false, type logical),",
          "      InsertCurrentFQ = Table.AddColumn(InsertCurrentFY, \"IsCurrentFQ\", each if [FQuarternYear] = CurrentFQ then true else false, type logical),",
          "      InsertCurrentFP = Table.AddColumn(InsertCurrentFQ, \"IsCurrentFP\", each if [FPeriodnYear] = CurrentFP then true else false, type logical),",
          "      InsertCurrentFW = Table.AddColumn(InsertCurrentFP, \"IsCurrentFW\", each if [FWeeknYear] = InsertISOYrOffset then true else false, type logical),",
          "      InsertPYTD = Table.AddColumn(InsertCurrentFW, \"IsPYTD\", each if CurrentYear-1 = [Year] and [Day of Year] <= CurrentDateRecord{0}[Day of Year] then true else false, type logical),",
          "        ListPrevFYDates = List.Buffer( Table.SelectRows( Table.ExpandTableColumn( Table.NestedJoin(",
          "            Table.AddIndexColumn( Table.RenameColumns( Table.TransformColumnTypes( Table.FromList( List.Dates( PrevFiscalFirstDay, Number.From(CurrentFiscalFirstDay-PrevFiscalFirstDay),#duration(1,0,0,0)), Splitter.SplitByNothing()),{{\"Column1\", type date}}), {{\"Column1\", \"DateFY\"}}), \"Index\", 1, 1), {\"Index\"}, ",
          "            Table.AddIndexColumn( Table.RenameColumns( Table.TransformColumnTypes( Table.FromList( List.Dates( Date.AddYears( PrevFiscalFirstDay, -1), Number.From( PrevFiscalFirstDay - Date.AddYears( PrevFiscalFirstDay, -1)),#duration(1,0,0,0)), Splitter.SplitByNothing()),{{\"Column1\", type date}}), {{\"Column1\", \"DateFY\"}}), \"Index\", 1, 1)",
          "            , {\"Index\"}, \"Table\", JoinKind.LeftOuter), \"Table\", {\"DateFY\"}, {\"PrevDateFY\"}), each [DateFY] <= CurrentDate)[PrevDateFY] ),",
          "      InsertPFYTD = Table.AddColumn(InsertPYTD, \"IsPFYTD\", each if [Fiscal CurrYearOffset] = -1 and List.Contains(ListPrevFYDates, [Date] ) then true else false, type logical),",
          "      InsertNetWorkdays = if AddRelativeNetWorkdays = true then Table.AddColumn(InsertPFYTD, \"Relative Networkdays\", each fxNETWORKDAYS( StartDate, [Date], Holidays ), type number ) else InsertPFYTD,",
          "      fxNETWORKDAYS = (StartDate, EndDate, optional Holidays as list) =>",
          "        let",
          "          ListOfDates = List.Dates( StartDate, Number.From(EndDate-StartDate)+1, Duration.From(1) ),",
          "          DeleteHolidays = if Holidays = null then ListOfDates else List.Difference( ListOfDates, List.Transform(Holidays, Date.From )),",
          "          DeleteWeekends = List.Select( DeleteHolidays, each Date.DayOfWeek( _, Day.Monday) < 5 ),",
          "          CountDays = List.Count( DeleteWeekends)",
          "        in",
          "          CountDays,",
          "      RemoveToday = Table.RemoveColumns( if EndDate < CurrentDate then Table.SelectRows(InsertNetWorkdays, each ([Date] <> CurrentDate)) else InsertNetWorkdays, {\"Day of Year\", \"FiscalFirstDay\"}), ",
          "      ChType = Table.TransformColumnTypes(RemoveToday,{{\"Year\", Int64.Type}, {\"Quarter Number\", Int64.Type}, {\"Month\", Int64.Type}, {\"Day of Month\", Int64.Type}, {\"DateInt\", Int64.Type}, {\"Day of Week Number\", Int64.Type}, {\"ISO CurrYearOffset\", Int64.Type}, {\"ISO QuarternYear\", Int64.Type}, {\"ISO CurrQuarterOffset\", Int64.Type}, {\"Week Number\", Int64.Type}, {\"WeeknYear\", Int64.Type}, {\"MonthnYear\", Int64.Type}, {\"QuarternYear\", Int64.Type}, {\"FQuarternYear\", Int64.Type}, {\"Fiscal Period Number\", Int64.Type}, {\"FPeriodnYear\", Int64.Type}, {\"CurrWeekOffset\", Int64.Type}, {\"CurrMonthOffset\", Int64.Type}, {\"CurrQuarterOffset\", Int64.Type}, {\"CurrYearOffset\", Int64.Type}, {\"Fiscal CurrYearOffset\", Int64.Type}, {\"Fiscal Week Number\", Int64.Type}}),",
          "      ReorderCols = Table.ReorderColumns(ChType,{\"Date\", \"Year\", \"CurrYearOffset\", \"YearCompleted\", \"Quarter Number\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Quarter & Year\", \"QuarternYear\", \"CurrQuarterOffset\", \"QuarterCompleted\", \"Month\", \"Start of Month\", \"End of Month\", \"Month & Year\", \"MonthnYear\", \"CurrMonthOffset\", \"MonthCompleted\", \"Month Name\", \"Month Short\", \"Month Initial\", \"Day of Month\", \"Week Number\", \"Start of Week\", \"End of Week\", \"Week & Year\", \"WeeknYear\", \"CurrWeekOffset\", \"WeekCompleted\", \"Day of Week Number\", \"Day of Week Name\", \"Day of Week Initial\", \"DateInt\", \"CurrDayOffset\", \"IsAfterToday\", \"IsWeekDay\", \"IsHoliday\", \"IsBusinessDay\", \"Day Type\", \"ISO Year\", \"ISO CurrYearOffset\", \"ISO Quarter Number\", \"ISO Quarter\", \"ISO Quarter & Year\", \"ISO QuarternYear\", \"ISO CurrQuarterOffset\", \"Fiscal Year\", \"Fiscal CurrYearOffset\", \"Fiscal Quarter\", \"FQuarternYear\", \"Fiscal Period Number\", \"Fiscal Period\", \"FPeriodnYear\", \"DateFW\", \"Fiscal Week Number\", \"Fiscal Week\", \"FWeeknYear\", \"IsCurrentFY\", \"IsCurrentFQ\", \"IsCurrentFP\", \"IsCurrentFW\", \"IsPYTD\", \"IsPFYTD\"}),",
          "      ListCols = if FWlogic then Table.RemoveColumns(ReorderCols,{\"ISO Quarter Number\", \"Fiscal Year\", \"Fiscal Quarter\", \"FQuarternYear\", \"Fiscal Period Number\", \"Fiscal Period\", \"FPeriodnYear\", \"DateFW\", \"Fiscal Week Number\", \"Fiscal Week\", \"FWeeknYear\", \"Fiscal CurrYearOffset\", \"IsCurrentFQ\", \"IsCurrentFP\", \"IsCurrentFW\"}) else Table.RemoveColumns(ReorderCols,{\"Fiscal Period Number\", \"DateFW\", \"Fiscal Week Number\", \"ISO Quarter Number\"})",
          "  in",
          "      ListCols,",
          "      Documentation = [",
          "      Documentation.Name =  \" fxCalendar\", ",
          "      Documentation.Description = \" Date table function to create an ISO-8601 calendar\", ",
          "      Documentation.LongDescription = \" Date table function to create an ISO-8601 calendar\", ",
          "      Documentation.Category = \" Table\", ",
          "      Documentation.Version = \" 2.01: full code review\",",
          "      Documentation.Source = \" local\", ",
          "      Documentation.Author = \" Melissa de Korte\", ",
          "      Documentation.Examples = { [Description =  \" See: https://forum.enterprisedna.co/t/extended-date-table-power-query-m-function/6390\", ",
          "        Code = \" Optional paramters: #(lf)",
          "        (FYStartMonthNum) Month number the fiscal year starts, Januari if omitted #(lf) ",
          "        (Holidays) Select a query (and column) that contains a list of holiday dates #(lf) ",
          "        (WDStartNum) Switch default weekday numbering from 0-6 to 1-7 by entering a 1 #(lf)",
          "        (AddRelativeNetWorkdays) if true adds a Relative Networkdays column to the date table #(lf)",
          "        #(lf)",
          "        Important to note: #(lf)",
          "        [Fiscal Week] starts on a Monday and can contain less than 7 days in a First- and/or Last Week of a FY #(lf)",
          "        [IsWeekDay] does not take holiday dates into account  #(lf)",
          "        [IsBusinessDay] does take optional holiday dates into account  #(lf)",
          "        [IsPYTD] and [IsPFYTD] compare Previous [Day of Year] with the Current [Day of Year] number, so dates don't align in leap years #(lf)",
          "        IMPORTANT! No Fiscal columns will be added if the (FYStartMonthNum) is omitted\", ",
          "        Result = \" \" ] }",
          "      ]",
          "  in ",
          "  Value.ReplaceType( fnDateTable, Value.ReplaceMetadata( Value.Type( fnDateTable ), Documentation ))",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d423f4b5-4b99-48ad-b946-3192de1aef5a",
        "queryGroup": "Parameters and Functions"
      },
      {
        "name": "fxStartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = Date.StartOfYear(List.Min(#\"fctTonnage\"[RepPeriod]))",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d824706b-4afb-47d1-b124-bd57da0e048e",
        "queryGroup": "Parameters and Functions"
      },
      {
        "name": "fxEndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = Date.EndOfYear(List.Max(#\"fctTonnage\"[RepPeriod]))",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b74561ea-d449-412c-808b-932abbc86b8f",
        "queryGroup": "Parameters and Functions"
      },
      {
        "name": "M_ComplianceReport_MetroWetActuals",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    ",
          "    // Data source",
          "    Source = Csv.Document(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Untitled - Compliance\\Other Files\\M_ComplianceReport_MetroWetActuals.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    ",
          "    // Promote first row of csv file as headers",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    ",
          "    // Set column data types",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"RepPeriod\", type date}, {\"Actuals\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "0fda65b0-e0a6-480a-8406-b27490f311b3",
        "queryGroup": "Source"
      }
    ],
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-01",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "defaults": {
            "firstDayOfWeek": 0
          },
          "description": "Standard gregorian calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 1,
          "holidaysEnabled": true,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 1,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [
            "Total Actuals",
            "Total Expected"
          ],
          "templateUri": "file:///C:/Users/Sherman/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Source queries only, before any transformations",
        "folder": "Source"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters and Functions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Containers"
      }
    ],
    "relationships": [
      {
        "name": "ebed3290-bb59-465d-bf4e-5d0ea617709e",
        "fromColumn": "VintageID",
        "fromTable": "fctWetCYForecasts",
        "toColumn": "VintageID",
        "toTable": "dimForecastVintage"
      },
      {
        "name": "c3d29721-7c91-4c8f-b20d-45d011e79cf4",
        "fromColumn": "RegulatoryInstrumentLimitId",
        "fromTable": "fctTonnage",
        "toColumn": "RegulatoryInstrumentID",
        "toTable": "dimRegulatoryInstrument"
      },
      {
        "name": "9a0333c7-09c6-4308-935d-beca7a51c0ca",
        "fromColumn": "RepPeriod",
        "fromTable": "fctTonnage",
        "toColumn": "Date",
        "toTable": "dimDate"
      },
      {
        "name": "55cf4c90-b43c-4b78-af68-14e790e73078",
        "fromColumn": "RepPeriod",
        "fromTable": "fctWetCYForecasts",
        "toColumn": "Date",
        "toTable": "dimDate"
      },
      {
        "name": "ee471122-0fd8-46cf-9887-ca08e1b7a472",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "dimDate",
        "toColumn": "RepPeriod",
        "toTable": "fctWetCYActuals"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Utilization",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2670d8acb9994e12a8ed646b34059375"
          }
        ],
        "columns": [
          {
            "name": "Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a0a4429e-02d4-456c-a3ea-d917df443750",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Utilization parameter",
        "lineageTag": "488880ab-19a1-48f8-9aad-f9d212ad2231",
        "partitions": [
          {
            "name": "Utilization-7dce5a6a-788c-46ff-88eb-c10e3ffa61ff",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(50, 100, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_DataRefresh",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4a3ff232-f375-47e3-92c9-256a9dcbf6e0",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "02b6c487-5681-4839-a1fa-675a49bdf76b",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isHidden": true,
            "lineageTag": "2e191852-985d-4f68-bd1b-ce1032b82910",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "description": "Holds model refresh statistics",
        "lineageTag": "76a15fec-3597-4253-b7cc-f42aabdf31d3",
        "partitions": [
          {
            "name": "_DataRefresh-e6c9ec01-4aab-4406-aa48-ada25aeffa8c",
            "mode": "import",
            "queryGroup": "Containers",
            "source": {
              "expression": [
                "let",
                "",
                "SummerTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 3, 14), Day.Sunday),",
                "WinterTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 10, 14), Day.Sunday),",
                "",
                "Timezonehours = if DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) < SummerTimeStartDate & #time(1, 0, 0) or",
                "DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) > WinterTimeStartDate & #time(1, 0, 0) then",
                "-8 else -7,",
                "",
                "#\"Date and Time\" = DateTimeZone.SwitchZone(DateTimeZone.UtcNow(), Timezonehours, 0),",
                "",
                "#\"Converted to Table\" = #table(1, {{#\"Date and Time\"}}),",
                "",
                "#\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "",
                "#\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"DateTime\", type datetimezone}}),",
                "",
                "#\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"DateTime\", \"DateTime - Copy\"),",
                "",
                "#\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "",
                "#\"Duplicated Column1\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Date\", \"Date - Copy\"),",
                "",
                "#\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column1\",{{\"Date - Copy\", type time}, {\"Date\", type date}}),",
                "",
                "#\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Date - Copy\", \"Time\"}})",
                "in",
                "",
                "#\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "Measure container",
        "lineageTag": "992bf3e3-40a3-41cc-a88e-e1e037c31404",
        "measures": [
          {
            "name": "Total Actuals",
            "description": "Computes the total actual tonnage from fctTonnage table",
            "displayFolder": "Base",
            "expression": "SUM('fctTonnage'[ActualTons])",
            "formatString": "0",
            "lineageTag": "8951aee2-bac3-4b3a-a9dc-ce62503cf00d"
          },
          {
            "name": "Total Expected",
            "description": "Computes total expected tonnage from fctTonnage table.  Expected tonnage is computed upstream (db server) using seasonal factors based on unique arcs (i.e. unique combinations of reporting entity, direction and material).",
            "displayFolder": "Base",
            "expression": "SUM('fctTonnage'[ExpectedTons])",
            "formatString": "0",
            "lineageTag": "07531c4f-e23d-4eff-956e-39fada755b43"
          },
          {
            "name": "YTD Total Actuals",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "description": "Computes calendar year-to-date total actual tonnage, using [Total Actuals] measure",
            "displayFolder": "Derivative",
            "expression": [
              "",
              "IF(",
              "    [ShowValueForDates],",
              "    CALCULATE (",
              "            [Total Actuals],",
              "            DATESYTD ( dimDate[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "2664c4c5-c78b-4f73-a962-a918c5bb8461"
          },
          {
            "name": "YTD Total Expected",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "description": "Computes calendar year-to-date total expected tonnage, using [Total Expected] measure",
            "displayFolder": "Derivative",
            "expression": [
              "",
              "IF (",
              "    [ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Expected],",
              "        DATESYTD ( dimDate[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "665429ff-0915-4010-a6c1-c14754753ad1"
          },
          {
            "name": "Limits",
            "description": "Computes the total tonnage limit in the dimRegulatoryInstrument table",
            "displayFolder": "Base",
            "expression": [
              "IF(",
              "    [ShowValueForDates],",
              "    SUM(dimRegulatoryInstrument[TonnageLimit])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "234c485c-c93a-4bbe-9b1f-57c2fa636bf4"
          },
          {
            "name": "Full Yr Estimate",
            "description": "Computes the full year estimated tonnage as the year-to-date actual tonnage divided by the year-to-date expected tonnage, multiplied by the tonnage limit",
            "displayFolder": "Derivative",
            "expression": "DIVIDE([YTD Total Actuals], [YTD Total Expected])*[Limits]",
            "formatString": "0",
            "lineageTag": "5188176f-c579-43e6-91ef-f1f3affb5255"
          },
          {
            "name": "Exceed By",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR CurrentYear = YEAR(MAX(dimDate[Date]))",
              "VAR StartDate = DATE(CurrentYear, 1, 1)",
              "VAR DaysToAdd = DIVIDE([Limits], [Full Yr Estimate])*365",
              "VAR ExceedDate = StartDate + DaysToAdd",
              "VAR Result = IF([Full Yr Estimate]>[Limits],FORMAT(ExceedDate, \"mmm yyyy\"),\"\")",
              "RETURN",
              "Result"
            ],
            "formatString": "mmm yyyy",
            "lineageTag": "89f9b1e2-21ff-4f83-ae52-302ec515b08f"
          },
          {
            "name": "AC",
            "description": "Presents the AC value for the Zebra BI table based on the users' selected period",
            "displayFolder": "Derivative",
            "expression": [
              "",
              "SWITCH( [Selected Period],",
              "    1, [Total Actuals],",
              "    2, [YTD Total Actuals],",
              "    3, [Full Yr Estimate]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "934019d5-7711-47fb-b798-53a300e3d375"
          },
          {
            "name": "PL",
            "description": "Presents the PL value for the Zebra BI table based on the users' selected period",
            "displayFolder": "Derivative",
            "expression": [
              "",
              "SWITCH( [Selected Period],",
              "    1, [Total Expected],",
              "    2, [YTD Total Expected],",
              "    3, [Limits]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "15bb4766-0f7d-4d33-9d54-d167273f2abb"
          },
          {
            "name": "Slicer Filter",
            "description": "The \"Alberto\", ensures that slicers do not return visuals with no data",
            "displayFolder": "Special Filters",
            "expression": [
              "",
              "INT ( ",
              "    NOT ISEMPTY(",
              "        CALCULATETABLE(",
              "            fctTonnage,",
              "            fctTonnage[ActualTons]>0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e5a6b256-f099-4f24-a127-bc7d9b384656"
          },
          {
            "name": "Wet FC Card Title",
            "description": "Conditional formatting measure that sets the title of the Total Wet card, to display actuals (if December) or forecasts",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _Year = SELECTEDVALUE(dimDate[Year])",
              "VAR _Month = SELECTEDVALUE(dimDate[Month])",
              "VAR _Predicate = IF ( _Month <> 12, \" Forecast\", \" Actuals\" )",
              "VAR _Result = \"CY \"&_Year&\" Industry Sales\"&_Predicate",
              "RETURN",
              "_Result"
            ],
            "lineageTag": "06d4c2da-2af4-4d2d-81bf-9ce465f2ccfd"
          },
          {
            "name": "Wet CY Private",
            "description": "Computes the actual (if December) or expected (allocation * utilization) private facility wet tonnage for the selected year",
            "displayFolder": "Derivative",
            "expression": [
              "",
              "VAR _Utilization = SELECTEDVALUE(Utilization[Utilization])/100",
              "VAR _SelectedYear = YEAR(MAX('dimDate'[Date]))",
              "VAR _SelectedMonth = MONTH(MAX('dimDate'[Date]))",
              "VAR _Allocation = ",
              "    CALCULATE(",
              "        [Limits],",
              "        dimRegulatoryInstrument[AllocRelated] = TRUE(),",
              "        FILTER(",
              "            ALL(dimRegulatoryInstrument),",
              "            COUNTROWS(",
              "                RELATEDTABLE(fctTonnage)",
              "            ) > 0",
              "        ),",
              "        ALL(dimDate),",
              "        VALUES(dimDate[Year])",
              "    )",
              "VAR _Actuals = ",
              "    CALCULATE(",
              "        [Total Actuals],",
              "        FILTER(",
              "            ALL('dimDate'),",
              "            'dimDate'[Year] = _SelectedYear",
              "        )",
              "    )",
              "VAR _Results = ",
              "    IF(_SelectedMonth = 12,",
              "        _Actuals,",
              "        _Allocation * _Utilization",
              "    )",
              "RETURN _Results"
            ],
            "formatString": "#,0",
            "lineageTag": "496e5c78-ba11-4b9d-9ce3-806d375270de"
          },
          {
            "name": "Wet CY Metro",
            "description": "Computes the actual (if December) or expected (total wet - private) metro wet tonnage for the selected year",
            "displayFolder": "Derivative",
            "expression": "[Wet CY Totals] - [Wet CY Private]",
            "formatString": "#,0",
            "lineageTag": "89536e7c-be2c-476d-9f52-9337b6c91023"
          },
          {
            "name": "Wet CY Private %",
            "description": "Computes percentage of calendar year wet waste that flows to private facilities for selected year",
            "displayFolder": "Derivative",
            "expression": "DIVIDE([Wet CY Private], [Wet CY Totals])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ce2417a8-9d0f-48bc-9832-e157af3bf54c"
          },
          {
            "name": "Wet CY Metro %",
            "description": "Computes percentage of calendar year wet waste that flows to private facilities for selected year",
            "displayFolder": "Derivative",
            "expression": "1 - [Wet CY Private %]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0d27bb13-5212-4d2e-bfc5-e4bfd78cc706"
          },
          {
            "name": "Private",
            "description": "Displays information about Private facility expected or actual tons and percentage of the total wet for the calendar year",
            "displayFolder": "Cards and Labels",
            "expression": "FORMAT([Wet CY Private %], \"0.0%\")",
            "lineageTag": "76a8a0dd-a577-46b3-9a8c-ce90c0da423f"
          },
          {
            "name": "Metro",
            "description": "Displays information about Metro's expected or actual tons and it's percentage of the total wet for the calendar year",
            "displayFolder": "Cards and Labels",
            "expression": "FORMAT([Wet CY Metro %], \"0.0%\")",
            "lineageTag": "8b443504-dc7e-4995-ac20-b2339c455638"
          },
          {
            "name": "Overallocationtxt",
            "description": "Conditional formatting measure that computes the amount of tonnage overallocated of the status indicator for the private/metro wet share",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _Threshold = .6",
              "VAR _Result = ",
              "IF([Wet CY Private %]>_Threshold, ",
              "    FORMAT( ( [Wet CY Private %]- _Threshold ) * [Wet CY Totals], \"#,#\"), ",
              "    \"\" ",
              ")",
              "RETURN _Result"
            ],
            "lineageTag": "e12c84e3-59aa-4a8d-b8df-8628874085df"
          },
          {
            "name": "Wet CY Totals",
            "description": "Computes the calendar year (for the selected year) total wet waste as the actuals through the selected period, plus forecasts from then through December",
            "displayFolder": "Base",
            "expression": [
              "",
              "VAR SelectedYear = YEAR(MAX('dimDate'[Date]))",
              "VAR SelectedMonth = MONTH(MAX('dimDate'[Date]))",
              "",
              "VAR ActualsSum = CALCULATE(",
              "    SUM('fctWetCYActuals'[Actuals]),",
              "    FILTER(",
              "        ALL('dimDate'),",
              "        'dimDate'[Year] = SelectedYear &&",
              "        'dimDate'[Month] <= SelectedMonth",
              "    )",
              ")",
              "",
              "VAR ForecastSum = CALCULATE(",
              "    SUM('fctWetCYForecasts'[Forecast]),",
              "    FILTER(",
              "        ALL('dimDate'),",
              "        'dimDate'[Year] = SelectedYear &&",
              "        'dimDate'[Month] > SelectedMonth",
              "    )",
              ")",
              "",
              "RETURN",
              "    ActualsSum + ForecastSum"
            ],
            "formatString": "0",
            "lineageTag": "807600ca-0a00-4536-9cdc-081484bf9d77"
          },
          {
            "name": "Vintage Filter",
            "description": "Computes the total number of monthly values selected between Wet CY actuals (up to the selected period) and forecasts (after the selected period through December) to ensure no out-of-scope vintages appear in vintage dropdown",
            "displayFolder": "Special Filters",
            "expression": [
              "",
              "VAR _SelectedYear = YEAR(MAX('dimDate'[Date]))",
              "VAR _SelectedMonth = MONTH(MAX('dimDate'[Date]))",
              "",
              "VAR _ActualsCount = CALCULATE(",
              "    COUNT('fctWetCYActuals'[Actuals]),",
              "    FILTER(",
              "        ALL('dimDate'),",
              "        'dimDate'[Year] = _SelectedYear &&",
              "        'dimDate'[Month] <= _SelectedMonth",
              "    )",
              ")",
              "",
              "VAR _ForecastCount = CALCULATE(",
              "    COUNT('fctWetCYForecasts'[Forecast]),",
              "    FILTER(",
              "        ALL('dimDate'),",
              "        'dimDate'[Year] = _SelectedYear &&",
              "        'dimDate'[Month] > _SelectedMonth",
              "    )",
              ")",
              "",
              "RETURN",
              "    _ActualsCount + _ForecastCount"
            ],
            "formatString": "0",
            "lineageTag": "6161e34b-f094-4993-b4f2-6f4ea39c4285"
          },
          {
            "name": "SelectNewVintagetxt",
            "description": "Conditional formatting measure that sets the message of the select new vintage warning indicator",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _SpanCheck = [Vintage Filter]",
              "VAR _Message = \"Select a different forecast\"",
              "VAR _Result = IF(_SpanCheck<>12, _Message,\"\")",
              "RETURN _Result"
            ],
            "lineageTag": "3b0e1eab-a531-4d11-89d0-d6175c8f82dc"
          },
          {
            "name": "SelectNewVintagebck",
            "description": "Conditional formatting measure that sets the background transparency of the select new vintage warning indicator",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _SpanCheck = [Vintage Filter]",
              "VAR _Result = IF(_SpanCheck<>12, \"#FFFFFF\", \"#00FFFFFF\")",
              "RETURN _Result"
            ],
            "lineageTag": "283181d9-d1e9-4dfb-a87c-f1720c384fbf"
          },
          {
            "name": "Overallocationtle",
            "description": "Conditional formatting measure that sets the title of the status indicator for the private/metro wet share",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _Threshold = .6",
              "VAR _Result = ",
              "IF([Wet CY Private %]>_Threshold, ",
              "    \"Work Harder!\",",
              "    \"All good here!\"",
              ")",
              "RETURN _Result"
            ],
            "lineageTag": "6ca846b6-4721-4556-ab70-56a8f548feaa"
          },
          {
            "name": "Overallocationclr",
            "description": "Conditional formatting measure that sets the font color of the status indicator for the private/metro wet share",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _Threshold = .6",
              "VAR _Result = ",
              "IF([Wet CY Private %]>_Threshold, ",
              "    \"#FF0000\",",
              "    \"#7aca00\"",
              ")",
              "RETURN _Result"
            ],
            "lineageTag": "a0ddb5a2-0d19-4133-8fd9-236bd008b060"
          },
          {
            "name": "Report Title",
            "description": "Displays a dynamic report title label",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _SelPeriod = SELECTEDVALUE(dimDate[Month & Year])",
              "VAR _Result = \"Executive Cost Report for \"&_SelPeriod",
              "RETURN _Result"
            ],
            "lineageTag": "c5e6e7b4-69e1-4455-b99d-8a63fcfd8b62"
          },
          {
            "name": "DataInfo",
            "description": "Displays information about the data currency and last refresh",
            "displayFolder": "Cards and Labels",
            "expression": [
              "",
              "VAR _LastDatesByFacility = ",
              "SUMMARIZE ( fctTonnage, ",
              "    fctTonnage[RegulatoryInstrumentLimitId], ",
              "    \"Max Date\", CALCULATE ( MAX ( fctTonnage[RepPeriod] ), dimRegulatoryInstrument[Inactive] = FALSE() ) )",
              "VAR _MinList = FORMAT(MINX ( _LastDatesByFacility, [Max Date] ), \"mmm yyyy\")",
              "VAR _Refresh = MAX( _DataRefresh[DateTime] )",
              "VAR _Result = \"Last period reported for products is \" & _MinList & \" and last refreshed on \" & _Refresh",
              "RETURN _Result"
            ],
            "lineageTag": "b03276c2-3811-4ad7-930e-aaf5aac532b2"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-1d2926fd-a1c3-416d-bfee-34dbe78a4946",
            "mode": "import",
            "queryGroup": "Containers",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Period",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b945214e-6a30-4908-a138-ef59c860b165",
            "sortByColumn": "Period ID",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "Period ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d3b4552-1e5f-48c4-a08d-95e0c770e8d7",
            "sourceColumn": "Period ID",
            "summarizeBy": "none"
          }
        ],
        "description": "Parameter table for periods",
        "lineageTag": "d51d06f3-cef5-4238-a4f6-ad9ac0af9119",
        "measures": [
          {
            "name": "Selected Period",
            "expression": "MIN(_Period[Period ID])",
            "formatString": "0",
            "lineageTag": "8ca5e47e-3d59-45a1-a167-d85a1ea423c7"
          }
        ],
        "partitions": [
          {
            "name": "_Period-eb43a518-d5e5-42ce-9235-6c7778cd7c8f",
            "mode": "import",
            "queryGroup": "Containers",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUfLNzyvJUIrViVYyAvIiQ1zAbGMg2600J0chMjWxSCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Period ID\" = _t, Period = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Period ID\", Int64.Type}, {\"Period\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CurrYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Year helper column: how many years date is from current year (is always <=0)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0c99a076-2207-4b8c-ad17-1926e6745bd1",
            "sourceColumn": "CurrYearOffset",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "primary key",
            "formatString": "mm/dd/yy",
            "lineageTag": "ef1ff686-6eee-4409-bc07-16915353633d",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateWithData",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "dimDate[Date] <= MAX ( fctTonnage[RepPeriod] )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "225bd252-3a62-4366-a858-872513fbcbad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "month number (1 - 12)",
            "formatString": "0",
            "lineageTag": "69c0d62e-807a-440d-bc24-c47bbd938244",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "month year string for visuals",
            "lineageTag": "bd3675d0-189d-4c41-8cb7-324921273527",
            "sortByColumn": "MonthnYear",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none"
          },
          {
            "name": "MonthCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "description": "month helper column: whether month of the date is completed (for showing only completed months)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "d590f26e-77ac-46f2-8bd9-6b81b870b0f7",
            "sourceColumn": "MonthCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "month & year helper: used to sort",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fce59c2d-bc38-491c-b041-1ba3b50366c7",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "quarter number (1 - 4)",
            "formatString": "0",
            "lineageTag": "68d8009a-cb41-4efc-b097-af12cb89f287",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "605df38a-b808-4008-9658-078377115882",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "first of the month for the current date",
            "formatString": "mm/dd/yy",
            "lineageTag": "2965c7fa-2ba8-4ab5-b60b-c693f02fd959",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "calendar year",
            "formatString": "0",
            "lineageTag": "bf31e712-34ff-43c1-8804-3b03cfe2444c",
            "sortByColumn": "CurrYearOffset",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "YearCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "description": "Year helper column: whether year of the date is completed (for showing only completed years)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "64c11bc5-11ce-42e7-ac0e-af3944b1009d",
            "sourceColumn": "YearCompleted",
            "summarizeBy": "none"
          }
        ],
        "description": "Calendar table (Dynamic M Date Table, by Melissa de Korte)",
        "lineageTag": "1cb9fdea-6e64-49fd-926e-46ee9e1b60e2",
        "measures": [
          {
            "name": "ShowValueForDates",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "This calculation determines whether the first date visible in the data set is before or after the last date with data",
              "=====",
              "",
              "VAR LastDateWithData =",
              "    CALCULATE (",
              "        MAX ( fctTonnage[RepPeriod] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR FirstDateVisible =",
              "    MIN ( dimDate[Date] )",
              "VAR Result =",
              "    FirstDateVisible <= LastDateWithData",
              "RETURN",
              "    Result"
            ],
            "expression": [
              "",
              "VAR LastDateWithData =",
              "    CALCULATE (",
              "        MAX ( fctTonnage[RepPeriod] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR FirstDateVisible =",
              "    MIN ( dimDate[Date] )",
              "VAR Result =",
              "    FirstDateVisible <= LastDateWithData",
              "RETURN",
              "    Result"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "293640e7-4caa-4dfc-a16f-e3b57e7d4e74"
          }
        ],
        "partitions": [
          {
            "name": "dimDate-03502966-729e-4bb0-be8b-1a84bae69eda",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = fxDateTable(fxStartDate, fxEndDate, 7, null, null, null)",
                ",",
                "// Post-report column removal by Measure Killer",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    Source,{\"Fiscal Week\",\"Week & Year\",\"DateInt\",\"Fiscal Period\",\"CurrDayOffset\",\"ISO Quarter & Year\",\"Fiscal Quarter\",\"Quarter & Year\",\"Month Initial\",\"Month Name\",\"Month Short\",\"Fiscal Year\",\"Quarter\",\"ISO Quarter\",\"Day of Week Name\",\"Day of Week Initial\",\"Day Type\",\"IsHoliday\",\"End of Month\",\"FWeeknYear\",\"End of Week\",\"Start of Week\",\"WeeknYear\",\"FPeriodnYear\",\"CurrMonthOffset\",\"CurrWeekOffset\",\"Week Number\",\"End of Quarter\",\"Start of Quarter\",\"ISO QuarternYear\",\"ISO CurrQuarterOffset\",\"FQuarternYear\",\"CurrQuarterOffset\",\"Day of Month\",\"Fiscal CurrYearOffset\",\"ISO CurrYearOffset\",\"ISO Year\",\"Day of Week Number\",\"IsBusinessDay\",\"IsWeekDay\",\"IsPFYTD\",\"IsCurrentFQ\",\"IsPYTD\",\"IsCurrentFP\",\"IsAfterToday\",\"IsCurrentFY\",\"WeekCompleted\",\"QuarterCompleted\",\"IsCurrentFW\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimForecastVintage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Sort column to ensure VintageName sorts from oldest to newest",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "f2d65131-5679-4cfe-a253-b9643f5f9225",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "VintageID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "primary key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "853c0f78-9e4a-4c25-b619-2bf954c87615",
            "sourceColumn": "VintageID",
            "summarizeBy": "none"
          },
          {
            "name": "VintageName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "Vintage name.  Most \"official\" wet forecasts using the Fall vintage of the previous year; so if the current purview of the report is 2023, use Fall 2022 vintage",
            "lineageTag": "461805d9-f268-4d3d-97f5-918d5eca5e2b",
            "sortByColumn": "Date",
            "sourceColumn": "VintageName",
            "summarizeBy": "none"
          }
        ],
        "description": "Vintage names",
        "lineageTag": "991be43f-3e71-428e-91cc-a206ef2803cb",
        "partitions": [
          {
            "name": "dimForecastVintage-4d83e240-d5e9-485c-8574-577c3bb7cd6e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Reference source query",
                "    Source = M_ComplianceReport_WetForecasts,",
                "",
                "    // Select vintage name",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"VintageName\"}),",
                "",
                "    // De-duplicate",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "",
                "    // Add primary key",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "",
                "    // Tidy-up",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"VintageName\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"VintageID\"}}),",
                "",
                "    // Create a sort column for Vintage",
                "    AddDateColumn = Table.AddColumn(#\"Renamed Columns\", \"Date\", each ",
                "        let",
                "            Vintage = Text.Split([VintageName], \" \"),",
                "            Season = Vintage{0},",
                "            Year = Number.FromText(Vintage{1}),",
                "            Month = ",
                "                if Season = \"Fall\" then 10 ",
                "                else if Season = \"Annual\" then 10",
                "                else if Season = \"Winter\" then 1 ",
                "                else if Season = \"Spring\" then 4 ",
                "                else if Season = \"Summer\" then 7 ",
                "                else null ",
                "        in ",
                "            #date(Year, Month, 1)),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(AddDateColumn,{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimRegulatoryInstrument",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "AllocRelated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "description": "Binary indicating whether the instrument pertains to wet waste tonnage allocations or not",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "31bccd75-94b7-4199-b448-3a3057b76484",
            "sourceColumn": "AllocRelated",
            "summarizeBy": "none"
          },
          {
            "name": "Destination",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The destination governed by the instrument limit.  If the instrument governs multiple destinations, \"Multiple destinations\" is used.",
            "lineageTag": "548ced00-4823-4ee8-aaa2-d5f7b61824f5",
            "sourceColumn": "Destination",
            "summarizeBy": "none"
          },
          {
            "name": "Direction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Whether the instrument governs incoming flows or outgoing flows",
            "lineageTag": "df3da23f-647c-4150-864b-e98da227a5c2",
            "sourceColumn": "Direction",
            "summarizeBy": "none"
          },
          {
            "name": "Inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "description": "indicates whether the instrument is active (0) or inactive (1).",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "987a3aea-5eb8-42b0-b1f2-29acac053392",
            "sourceColumn": "Inactive",
            "summarizeBy": "none"
          },
          {
            "name": "InstrumentLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "Full instrument label",
            "lineageTag": "f37df8f2-d256-4dfb-af96-12d6b3b1e98a",
            "sortByColumn": "ReferenceNumber",
            "sourceColumn": "InstrumentLabel",
            "summarizeBy": "none"
          },
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The material that the instrument governs.  If the instrument governs multple material types, \"Multiple materials\" is used.",
            "lineageTag": "7c8e1384-d68c-470a-8302-924febca5027",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "P&C tag/identifier for the instrument",
            "lineageTag": "6952298e-b6ce-47f3-b863-36ba0c3595f8",
            "sourceColumn": "ReferenceNumber",
            "summarizeBy": "none"
          },
          {
            "name": "RegulatoryInstrumentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "primary key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c028ac83-6d82-4644-8322-9431e1b1c526",
            "sourceColumn": "RegulatoryInstrumentID",
            "summarizeBy": "none"
          },
          {
            "name": "ReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Facility, hauler or generator which owns the instrument.  If the instrument is owned by multiple entities, \"Multiple entities\" is used.",
            "lineageTag": "bb1526ca-ed11-4526-a496-0b23ed6639ac",
            "sourceColumn": "ReportingEntity",
            "summarizeBy": "none"
          },
          {
            "name": "TonnageLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "tonnage limit associated with instrument",
            "formatString": "0,0",
            "isHidden": true,
            "lineageTag": "b26aefad-b09a-43d2-bc16-7861a92496bb",
            "sourceColumn": "TonnageLimit",
            "summarizeBy": "none"
          }
        ],
        "description": "Regulatory instruments, including their tonnage limits and other metadata",
        "lineageTag": "eb9b451b-1c0d-4de9-9874-40232b12d4d7",
        "partitions": [
          {
            "name": "dimRegulatoryInstrument-d18a226e-0439-497e-8c4a-69bf682f540e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Source Reference",
                "    Source = M_ComplianceReport_ActualsExpected,",
                "    ",
                "    // Remove tonnage-related columns",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"RepPeriod\", \"ActualTons\", \"ExpectedTons\"}),",
                "    ",
                "    // Rename id column to conform to dim table name",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"RegulatoryInstrumentLimitId\", \"RegulatoryInstrumentID\"}}),",
                "    ",
                "    // De-duplicate ids",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Renamed Columns\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"Inactive\", type logical}, {\"AllocRelated\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fctTonnage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "ActualTons",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "actual tons accrued to the reporting period",
            "isHidden": true,
            "lineageTag": "a5e237eb-7d47-44a6-8da6-0ddf7a7b227e",
            "sourceColumn": "ActualTons",
            "summarizeBy": "none"
          },
          {
            "name": "ExpectedTons",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "expected tons accrued to the reporting period",
            "isHidden": true,
            "lineageTag": "4131a49f-c631-4289-acf5-624a6f891581",
            "sourceColumn": "ExpectedTons",
            "summarizeBy": "none"
          },
          {
            "name": "RegulatoryInstrumentLimitId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "foreign key to regulatory instrument table",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2574c2ba-258e-4c67-90c5-ec17fa045aa8",
            "sourceColumn": "RegulatoryInstrumentLimitId",
            "summarizeBy": "none"
          },
          {
            "name": "RepPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "foreign key to calendar table",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "879b37ae-d946-4c8b-98f0-ec2f04fcd3cb",
            "sourceColumn": "RepPeriod",
            "summarizeBy": "none"
          }
        ],
        "description": "Monthly tonnage accruals by instrument",
        "isHidden": true,
        "lineageTag": "667285af-5e85-411f-9d24-57523e0402b7",
        "partitions": [
          {
            "name": "fctTonnage-41bbb42e-6f01-41f0-b02d-8fabd1a13dee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Reference source query",
                "    Source = M_ComplianceReport_ActualsExpected,",
                "    ",
                "    // Remove reg instrument-related columns",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"InstrumentLabel\", \"ReferenceNumber\", \"ReportingEntity\", \"Direction\", \"Material\", \"Destination\", \"TonnageLimit\", \"AllocRelated\", \"Inactive\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fctWetCYActuals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Actuals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff4496b4-94a5-4f2b-9946-ff1e079cc00e",
            "sourceColumn": "Actuals",
            "summarizeBy": "none"
          },
          {
            "name": "RepPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "foreign key to date table",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "33ddd4e0-9e79-4568-a69c-363191940fa7",
            "sourceColumn": "RepPeriod",
            "summarizeBy": "none"
          }
        ],
        "description": "Wet waste actuals by period",
        "isHidden": true,
        "lineageTag": "eecab1a4-b499-4b01-ad61-c23100185b5c",
        "partitions": [
          {
            "name": "fctWetCYActuals-4c6fbd9c-09db-4bba-8ce7-71294fcebc59",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Reference source query",
                "    Source = M_ComplianceReport_ActualsExpected,",
                "    ",
                "    // Select only wet allocation-related tonnage records",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([AllocRelated] = 1)),",
                "    ",
                "    // Pivot on reporting period and sum actual tonnage",
                "    #\"Grouped Rows\" = Table.Group(#\"Filtered Rows\", {\"RepPeriod\"}, {{\"Actuals\", each List.Sum([ActualTons]), type nullable number}}),",
                "    ",
                "    // Rename tonnage to private actuals",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Grouped Rows\",{{\"Actuals\", \"Private Actuals\"}}),",
                "    ",
                "    // Merge metro tonnage actuals",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"RepPeriod\"}, M_ComplianceReport_MetroWetActuals, {\"RepPeriod\"}, \"M_ComplianceReport_MetroWetActuals\", JoinKind.LeftOuter),",
                "    #\"Expanded M_ComplianceReport_MetroWetActuals\" = Table.ExpandTableColumn(#\"Merged Queries\", \"M_ComplianceReport_MetroWetActuals\", {\"Actuals\"}, {\"Actuals\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded M_ComplianceReport_MetroWetActuals\",{{\"Actuals\", \"Metro Actuals\"}}),",
                "    ",
                "    // Sum private and metro actuals into a single actuals column",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Actuals\", each [Private Actuals] + [Metro Actuals]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Actuals\", Int64.Type}}),",
                "    ",
                "    // Remove the individual private and metro actuals columns",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Private Actuals\", \"Metro Actuals\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fctWetCYForecasts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Forecast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Amount of tons forecasted for the CY and vintage",
            "formatString": "0,0",
            "isHidden": true,
            "lineageTag": "dfe6c007-09f9-4b6a-8978-3c19a0aed0ca",
            "sourceColumn": "Forecast",
            "summarizeBy": "none"
          },
          {
            "name": "RepPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "foreign key to Calendar table",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "7d351fc5-cb19-48b1-b9dc-59eb5639b445",
            "sourceColumn": "RepPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "VintageID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "foreign key to the vintage table",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ac6f1141-4b4c-4b27-9d0f-34c3f078ab91",
            "sourceColumn": "VintageID",
            "summarizeBy": "none"
          }
        ],
        "description": "Wet waste forecasts by period and vintage",
        "isHidden": true,
        "lineageTag": "6b343646-3d74-47bc-89f6-cd7793fe6168",
        "partitions": [
          {
            "name": "fctWetCYForecasts-c0b9736f-701a-48bf-a42c-8a3d3908d6e3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Reference source query",
                "    Source = M_ComplianceReport_WetForecasts,",
                "",
                "    // Merge vintage id into vintage name and remove vintage name",
                "    #\"Merged Queries\" = Table.NestedJoin(Source, {\"VintageName\"}, dimForecastVintage, {\"VintageName\"}, \"dimForecastVintage\", JoinKind.LeftOuter),",
                "    #\"Expanded dimForecastVintage\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dimForecastVintage\", {\"VintageID\"}, {\"VintageID\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded dimForecastVintage\",{\"VintageName\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Tons\", \"Forecast\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}